<?php

namespace VOCS\PlatformBundle\Repository;

/**
 * ListsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListsRepository extends \Doctrine\ORM\EntityRepository
{
}
