<?php

namespace VOCS\PlatformBundle\Repository;

/**
 * ListsWordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListsWordsRepository extends \Doctrine\ORM\EntityRepository
{
    public function testListWord($list, $word, $trad) {
        $qb = $this->createQueryBuilder('lw');
        return $qb
            ->select('lw')
            ->where('') // $word = $wordContent + $wordLanguage
            ->orWhere()
    }
}
