<?php

namespace VOCS\PlatformBundle\Repository;

/**
 * SchoolsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCp() {

        $qb = $this->createQueryBuilder('c');
        return $qb->select('c.cp')->addSelect('c.id')->distinct()->orderBy('c.cp')->getQuery()->getResult();
    }



}
