<?php

namespace VOCS\PlatformBundle\Repository;

/**
 * SchoolsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolsRepository extends \Doctrine\ORM\EntityRepository
{
}
