<?php

namespace VOCS\PlatformBundle\Repository;

/**
 * WordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordsRepository extends \Doctrine\ORM\EntityRepository
{
}
